/* eslint-disable */
export enum QueryKeys {
  // business
  GET_ORGANIZATIONS = 'GET_ORGANIZATIONS',
  GET_PAGINATED_BUSINESSES = 'GET_PAGINATED_BUSINESSES',
  GET_BUSINESSES = 'GET_BUSINESSES',
  GET_BUSINESSES_BY_ID = 'GET_BUSINESS_BY_ID',

  // users and roles
  GET_ROLE_BY_ID = 'GET_ROLE_BY_ID',
  GET_ALL_ROLES = 'GET_ALL_ROLES',
  GET_ROLES_WITH_PAGINATION = 'GET_ROLES_WITH_PAGINATION',
  GET_ALL_USERS = 'GET_ALL_USERS',
  GET_INVITATION = 'GET_INVITATION',
  GET_USER_BY_ID = 'GET_USER_BY_ID',
}
